class ToolManager:
    def __init__(self):
        self.tools = {}

    def register(self, name, function):
        self.tools[name] = function

    def execute(self, name, **kwargs):
        if name not in self.tools:
            raise ValueError(f"Unknown tool: {name}")

        function = self.tools[name]

        # If the tool doesn't accept any arguments,
        # ignore arguments accidentally generated by the AI.
        if not kwargs:
            return function()

        import inspect

        parameters = inspect.signature(function).parameters

        # Keep only arguments the function actually accepts
        valid_kwargs = {
            key: value
            for key, value in kwargs.items()
            if key in parameters
        }

        return function(**valid_kwargs)

    def get_tool_names(self):
        return list(self.tools.keys())